package com.example.star.movie4share.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.star.movie4share.entity.Product;
import com.example.star.movie4share.entity.User;

import com.example.star.movie4share.dao.ProductDao;
import com.example.star.movie4share.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ProductDao productDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        productDao = new ProductDao(productDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Product.class, productDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        productDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
